# docker compose -p host-etcd -f compose.yaml up -d
# docker compose -p host-etcd down
# need compose.v2 https://github.com/docker/compose
version: "3.8"
services:
  pods-etcd:
    image: softlang/etcd:v3.3.11
    #registry.cn-hangzhou.aliyuncs.com/sdinc/etcd:v3.3.11
    #image: quay.io/coreos/etcd:v3.5.2
    hostname: etcd4dev
    container_name: etcd4dev
    entrypoint: /usr/local/bin/etcd
    command: --config-file=/config4etcd.yaml
    volumes:
      - ./data:/etcd_data
      - ./config.yaml:/config4etcd.yaml
    environment:
      TZ: "Asia/Shanghai"
      ETCDCTL_API: 3
      etcget: "etcdctl --user= get --prefix"
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health","--user=health:health"]
      interval: 60s
      timeout: 5s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
