# docker stack deploy --prune -c docker-compose.yaml etclus
version: '3.6'

volumes:
  etcd01:
  etcd02:
  etcd03:

services:
  etcd1:
    image: softlang/etcd-alpine:v3.4.14
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd1'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd1:2379'
      - '--initial-cluster-token=SoftlangNET'
      - '--heartbeat-interval=500'
      - '--election-timeout=2000'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 23791:2379
    volumes:
      - etcd01:/etcd_data
  etcd2:
    image: softlang/etcd-alpine:v3.4.14
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd2'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd2:2379'
      - '--initial-cluster-token=SoftlangNET'
      - '--heartbeat-interval=500'
      - '--election-timeout=2000'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 23792:2379
    volumes:
      - etcd02:/etcd_data
  etcd3:
    image: softlang/etcd-alpine:v3.4.14
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd3'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd3:2379'
      - '--initial-cluster-token=SoftlangNET'
      - '--heartbeat-interval=500'
      - '--election-timeout=2000'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 23793:2379
    volumes:
      - etcd03:/etcd_data